version: '3.9'

services:
  tapebackup:
    image: dzcr/tapebackup:latest
    build: Dockerfile
      #  - id=gcloud.json,src=$HOME/.keys/gcloud-cs221.json
    #container_name: optuna_worker
    #ports:
    #  - 8888:8888
    #volumes:
    #  - ./:/workspace
    #  - diskcache:/mnt/diskcache
    #  - artifacts:/mnt/artifacts
#    healthcheck:
#      test: curl --fail http://localhost || exit 1
#      interval: 60s
#      retries: 5
#      start_period: 20s
#      timeout: 10s
#    environment:
#      - JUPYTER_ENABLE_LAB=yes
#      - GRANT_SUDO=yes
#      - NB_UID=1000
#      - NB_GID=100
#      - CHOWN_HOME=yes
#      - CHOWN_HOME_OPTS='-R'
#      - CHOWN_EXTRA_OPTS='-R'
#      - N_TRIALS=${N_TRIALS:-100}
#      - N_PROCESSES=${N_PROCESSES:-2}
#    networks:
#      - isolated_network

volumes:
    database:
      driver: anybox/buttervolume:HEAD
      #external: true


#secrets:
#  gcloud.json:
#    file: ${HOME}/.keys/gcloud-cs221.json
#  alpaca.json:
#    file: ${HOME}/.keys/alpaca-paper.json
